version: '3'
services:
  backend:
    build:
      context: ./backend/
    ports:
      - "5000:8000"
    volumes:
      - ./src/backend/
    depends_on:
      - db
      - redis
    platform: linux/amd64


  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "2345:5432"


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    platform: linux/amd64

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "5173:80"
    platform: linux/amd64


